# volumes: (so the database can persist between docker restarts)

services:
  db:
    restart: unless-stopped
    hostname: db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-volume:/var/lib/mysql
  app:
    depends_on:
      - db
    restart: unless-stopped
    build: .
    ports:
      - "50050:50050"
    environment:
      DOCKER: true
      BACKEND_HOST: 0.0.0.0
      BACKEND_PORT: 50050
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
      DB_PORT: 3306
      JWT_SECRET_FILE: /run/secrets/jwt_secret
    secrets:
      - jwt_secret

secrets:
  jwt_secret:
    file: jwt_secret.txt

volumes:
  db-volume:
